CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL CHECK (name <> ''),
    description VARCHAR(200),
    releaseDate DATE,
    duration INT CHECK (duration > 0)
);
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    login VARCHAR(50) NOT NULL CHECK (login <> ''),
    name VARCHAR(200),
    birthday DATE
);
CREATE TABLE IF NOT EXISTS friends (
    senderUser_id BIGINT REFERENCES users(id),
    receiverUser_id BIGINT REFERENCES users(id),
    status BOOLEAN,
    PRIMARY KEY (senderUser_id, receiverUser_id)
);
CREATE TABLE IF NOT EXISTS films_likes (
    films_id BIGINT REFERENCES films(id),
    users_id BIGINT REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS films_genre (
    films_id BIGINT REFERENCES films(id),
    genre_id BIGINT REFERENCES genre(id)
);
CREATE TABLE IF NOT EXISTS rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS films_rating (
    films_id BIGINT REFERENCES films(id),
    rating_id BIGINT REFERENCES rating(id)
);
INSERT INTO rating (name) VALUES ('G'),('PG'),('PG-13'),('R'),('NC-17');
INSERT INTO genre (name) VALUES ('Комедия'),('Драма'),('Мультфильм'),('Триллер'),('Документальный'),('Боевик');