-- USERS
CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(64)  NOT NULL,
    name     VARCHAR(255),
    birthday DATE
);

-- MPA
CREATE TABLE IF NOT EXISTS mpa_ratings
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(16) NOT NULL UNIQUE
);

-- GENRES
CREATE TABLE IF NOT EXISTS genres
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

-- FILMS
CREATE TABLE IF NOT EXISTS films
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(200) NOT NULL DEFAULT '',
    release_date  DATE         NOT NULL,
    duration      INT          NOT NULL,
    mpa_rating_id SMALLINT,
    CONSTRAINT fk_films_mpa FOREIGN KEY (mpa_rating_id)
        REFERENCES mpa_ratings (id) ON DELETE RESTRICT
);

-- FRIENDSHIPS
CREATE TABLE IF NOT EXISTS friendships
(
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friend_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friend_friend FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE
);

-- LIKES
CREATE TABLE IF NOT EXISTS likes
(
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_like_film FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- FILM ↔ GENRES
CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  BIGINT   NOT NULL,
    genre_id SMALLINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_fg_film FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    CONSTRAINT fk_fg_genre FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE RESTRICT
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_friendships_friend ON friendships (friend_id);
CREATE INDEX IF NOT EXISTS idx_likes_user ON likes (user_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_genre ON film_genres (genre_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_film ON film_genres (film_id);
CREATE INDEX IF NOT EXISTS idx_films_mpa ON films (mpa_rating_id);
