CREATE TABLE IF NOT EXISTS rating_MPA (
                       rating_id INTEGER PRIMARY KEY,
                       name varchar(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
                       genre_id INTEGER PRIMARY KEY,
                       name varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                       film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) NOT NULL,
                       description varchar(200),
                       releaseDate date,
                       duration integer,
                       rating_id integer REFERENCES rating_MPA (rating_id),
                       likes_counter integer default '0'
);

CREATE TABLE IF NOT EXISTS film_genres (
                       film_id INTEGER REFERENCES films (film_id),
                       genre_id INTEGER REFERENCES genres (genre_id),
                       CONSTRAINT pkFilmGenres PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users (
                       user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email varchar(100) NOT NULL,
                       login varchar(50) NOT NULL,
                       name varchar(100) NOT NULL,
                       birthday date
);

CREATE TABLE IF NOT EXISTS friends (
                       user_id INTEGER REFERENCES users (user_id),
                       friend_id INTEGER REFERENCES users (user_id),
                       friendship_status varchar(20),
                       CONSTRAINT pkFriends PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes (
                       film_id INTEGER REFERENCES films (film_id),
                       user_id INTEGER REFERENCES users (user_id),
                       CONSTRAINT pkLikes PRIMARY KEY (film_id, user_id)
);