create table IF NOT EXISTS genres
(
    genre_id   int generated by default as identity,
    genre_name varchar(30)
    );

create table IF NOT EXISTS ratings
(
    rating_id   int generated by default as identity,
    rating_name varchar(30)
    );

create table IF NOT EXISTS films
(
    film_id     int generated by default as identity,
    film_name   varchar(30),
    description varchar(200),
    releaseDate date,
    duration    int,
    genre_id    int REFERENCES genres (genre_id),
    rating_id   int REFERENCES ratings (rating_id)
    );

create table IF NOT EXISTS film_genre
(
    film_id  int REFERENCES films (film_id),
    genre_id int REFERENCES genres (genre_id)
    );

create table IF NOT EXISTS user
(
    user_id  int generated by default as identity,
    name     varchar(30),
    email    varchar(30),
    login    varchar(30),
    birthday date
    );

create table IF NOT EXISTS likes
(
    like_id int generated by default as identity,
    user_id int REFERENCES user (user_id),
    film_id int REFERENCES films (film_id)
    );

create table IF NOT EXISTS statuses
(
    status_id   int generated by default as identity,
    status_name varchar(30)
    );

create table IF NOT EXISTS relationships
(
    relationship_id int generated by default as identity,
    user_id         int REFERENCES user (user_id),
    friend_id       int REFERENCES user (user_id),
    status_id       int REFERENCES statuses (status_id)
    );



